//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AUTOPECASModel", "FK_Pecas_Categorias1", "CATEGORIAS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Matriz.CATEGORIAS), "PECAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Matriz.PECAS), true)]
[assembly: EdmRelationshipAttribute("AUTOPECASModel", "FK_VENDA_REFERENCE_CLIENTES", "CLIENTES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Matriz.CLIENTES), "VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Matriz.VENDA), true)]
[assembly: EdmRelationshipAttribute("AUTOPECASModel", "FK_Pecas_Fornecedores", "FORNECEDORES", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Matriz.FORNECEDORES), "PECAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Matriz.PECAS), true)]
[assembly: EdmRelationshipAttribute("AUTOPECASModel", "FK_ITENSVEN_REFERENCE_VENDA", "VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Matriz.VENDA), "ITENSVENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Matriz.ITENSVENDA), true)]
[assembly: EdmRelationshipAttribute("AUTOPECASModel", "FK_ItensVenda_Pecas", "PECAS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Matriz.PECAS), "ITENSVENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Matriz.ITENSVENDA), true)]
[assembly: EdmRelationshipAttribute("AUTOPECASModel", "FK_Pecas_Veiculos", "VEICULOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Matriz.VEICULOS), "PECAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Matriz.PECAS), true)]
[assembly: EdmRelationshipAttribute("AUTOPECASModel", "FK_VENDA_REFERENCE_VENDEDOR", "VENDEDORES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Matriz.VENDEDORES), "VENDA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Matriz.VENDA), true)]

#endregion

namespace Matriz
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AUTOPECASEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AUTOPECASEntities2 object using the connection string found in the 'AUTOPECASEntities2' section of the application configuration file.
        /// </summary>
        public AUTOPECASEntities2() : base("name=AUTOPECASEntities2", "AUTOPECASEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AUTOPECASEntities2 object.
        /// </summary>
        public AUTOPECASEntities2(string connectionString) : base(connectionString, "AUTOPECASEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AUTOPECASEntities2 object.
        /// </summary>
        public AUTOPECASEntities2(EntityConnection connection) : base(connection, "AUTOPECASEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CATEGORIAS> CATEGORIAS
        {
            get
            {
                if ((_CATEGORIAS == null))
                {
                    _CATEGORIAS = base.CreateObjectSet<CATEGORIAS>("CATEGORIAS");
                }
                return _CATEGORIAS;
            }
        }
        private ObjectSet<CATEGORIAS> _CATEGORIAS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CLIENTES> CLIENTES
        {
            get
            {
                if ((_CLIENTES == null))
                {
                    _CLIENTES = base.CreateObjectSet<CLIENTES>("CLIENTES");
                }
                return _CLIENTES;
            }
        }
        private ObjectSet<CLIENTES> _CLIENTES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FORNECEDORES> FORNECEDORES
        {
            get
            {
                if ((_FORNECEDORES == null))
                {
                    _FORNECEDORES = base.CreateObjectSet<FORNECEDORES>("FORNECEDORES");
                }
                return _FORNECEDORES;
            }
        }
        private ObjectSet<FORNECEDORES> _FORNECEDORES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ITENSVENDA> ITENSVENDA
        {
            get
            {
                if ((_ITENSVENDA == null))
                {
                    _ITENSVENDA = base.CreateObjectSet<ITENSVENDA>("ITENSVENDA");
                }
                return _ITENSVENDA;
            }
        }
        private ObjectSet<ITENSVENDA> _ITENSVENDA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PECAS> PECAS
        {
            get
            {
                if ((_PECAS == null))
                {
                    _PECAS = base.CreateObjectSet<PECAS>("PECAS");
                }
                return _PECAS;
            }
        }
        private ObjectSet<PECAS> _PECAS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VEICULOS> VEICULOS
        {
            get
            {
                if ((_VEICULOS == null))
                {
                    _VEICULOS = base.CreateObjectSet<VEICULOS>("VEICULOS");
                }
                return _VEICULOS;
            }
        }
        private ObjectSet<VEICULOS> _VEICULOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VENDA> VENDA
        {
            get
            {
                if ((_VENDA == null))
                {
                    _VENDA = base.CreateObjectSet<VENDA>("VENDA");
                }
                return _VENDA;
            }
        }
        private ObjectSet<VENDA> _VENDA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VENDEDORES> VENDEDORES
        {
            get
            {
                if ((_VENDEDORES == null))
                {
                    _VENDEDORES = base.CreateObjectSet<VENDEDORES>("VENDEDORES");
                }
                return _VENDEDORES;
            }
        }
        private ObjectSet<VENDEDORES> _VENDEDORES;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CATEGORIAS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCATEGORIAS(CATEGORIAS cATEGORIAS)
        {
            base.AddObject("CATEGORIAS", cATEGORIAS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CLIENTES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCLIENTES(CLIENTES cLIENTES)
        {
            base.AddObject("CLIENTES", cLIENTES);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FORNECEDORES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFORNECEDORES(FORNECEDORES fORNECEDORES)
        {
            base.AddObject("FORNECEDORES", fORNECEDORES);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ITENSVENDA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToITENSVENDA(ITENSVENDA iTENSVENDA)
        {
            base.AddObject("ITENSVENDA", iTENSVENDA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PECAS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPECAS(PECAS pECAS)
        {
            base.AddObject("PECAS", pECAS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VEICULOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVEICULOS(VEICULOS vEICULOS)
        {
            base.AddObject("VEICULOS", vEICULOS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VENDA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVENDA(VENDA vENDA)
        {
            base.AddObject("VENDA", vENDA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VENDEDORES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVENDEDORES(VENDEDORES vENDEDORES)
        {
            base.AddObject("VENDEDORES", vENDEDORES);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AUTOPECASModel", Name="CATEGORIAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CATEGORIAS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CATEGORIAS object.
        /// </summary>
        /// <param name="iDCATEGORIA">Initial value of the IDCATEGORIA property.</param>
        /// <param name="nOMECATEGORIA">Initial value of the NOMECATEGORIA property.</param>
        public static CATEGORIAS CreateCATEGORIAS(global::System.Int32 iDCATEGORIA, global::System.String nOMECATEGORIA)
        {
            CATEGORIAS cATEGORIAS = new CATEGORIAS();
            cATEGORIAS.IDCATEGORIA = iDCATEGORIA;
            cATEGORIAS.NOMECATEGORIA = nOMECATEGORIA;
            return cATEGORIAS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCATEGORIA
        {
            get
            {
                return _IDCATEGORIA;
            }
            set
            {
                if (_IDCATEGORIA != value)
                {
                    OnIDCATEGORIAChanging(value);
                    ReportPropertyChanging("IDCATEGORIA");
                    _IDCATEGORIA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCATEGORIA");
                    OnIDCATEGORIAChanged();
                }
            }
        }
        private global::System.Int32 _IDCATEGORIA;
        partial void OnIDCATEGORIAChanging(global::System.Int32 value);
        partial void OnIDCATEGORIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMECATEGORIA
        {
            get
            {
                return _NOMECATEGORIA;
            }
            set
            {
                OnNOMECATEGORIAChanging(value);
                ReportPropertyChanging("NOMECATEGORIA");
                _NOMECATEGORIA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMECATEGORIA");
                OnNOMECATEGORIAChanged();
            }
        }
        private global::System.String _NOMECATEGORIA;
        partial void OnNOMECATEGORIAChanging(global::System.String value);
        partial void OnNOMECATEGORIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRICAO
        {
            get
            {
                return _DESCRICAO;
            }
            set
            {
                OnDESCRICAOChanging(value);
                ReportPropertyChanging("DESCRICAO");
                _DESCRICAO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRICAO");
                OnDESCRICAOChanged();
            }
        }
        private global::System.String _DESCRICAO;
        partial void OnDESCRICAOChanging(global::System.String value);
        partial void OnDESCRICAOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_Pecas_Categorias1", "PECAS")]
        public EntityCollection<PECAS> PECAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PECAS>("AUTOPECASModel.FK_Pecas_Categorias1", "PECAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PECAS>("AUTOPECASModel.FK_Pecas_Categorias1", "PECAS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AUTOPECASModel", Name="CLIENTES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CLIENTES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CLIENTES object.
        /// </summary>
        /// <param name="iDCLIENTE">Initial value of the IDCLIENTE property.</param>
        /// <param name="nOMECLIENTE">Initial value of the NOMECLIENTE property.</param>
        /// <param name="eNDERECOCLIENTE">Initial value of the ENDERECOCLIENTE property.</param>
        /// <param name="cEP">Initial value of the CEP property.</param>
        public static CLIENTES CreateCLIENTES(global::System.Int32 iDCLIENTE, global::System.String nOMECLIENTE, global::System.String eNDERECOCLIENTE, global::System.String cEP)
        {
            CLIENTES cLIENTES = new CLIENTES();
            cLIENTES.IDCLIENTE = iDCLIENTE;
            cLIENTES.NOMECLIENTE = nOMECLIENTE;
            cLIENTES.ENDERECOCLIENTE = eNDERECOCLIENTE;
            cLIENTES.CEP = cEP;
            return cLIENTES;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCLIENTE
        {
            get
            {
                return _IDCLIENTE;
            }
            set
            {
                if (_IDCLIENTE != value)
                {
                    OnIDCLIENTEChanging(value);
                    ReportPropertyChanging("IDCLIENTE");
                    _IDCLIENTE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDCLIENTE");
                    OnIDCLIENTEChanged();
                }
            }
        }
        private global::System.Int32 _IDCLIENTE;
        partial void OnIDCLIENTEChanging(global::System.Int32 value);
        partial void OnIDCLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMECLIENTE
        {
            get
            {
                return _NOMECLIENTE;
            }
            set
            {
                OnNOMECLIENTEChanging(value);
                ReportPropertyChanging("NOMECLIENTE");
                _NOMECLIENTE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMECLIENTE");
                OnNOMECLIENTEChanged();
            }
        }
        private global::System.String _NOMECLIENTE;
        partial void OnNOMECLIENTEChanging(global::System.String value);
        partial void OnNOMECLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CNPJ
        {
            get
            {
                return _CNPJ;
            }
            set
            {
                OnCNPJChanging(value);
                ReportPropertyChanging("CNPJ");
                _CNPJ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CNPJ");
                OnCNPJChanged();
            }
        }
        private global::System.String _CNPJ;
        partial void OnCNPJChanging(global::System.String value);
        partial void OnCNPJChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ENDERECOCLIENTE
        {
            get
            {
                return _ENDERECOCLIENTE;
            }
            set
            {
                OnENDERECOCLIENTEChanging(value);
                ReportPropertyChanging("ENDERECOCLIENTE");
                _ENDERECOCLIENTE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ENDERECOCLIENTE");
                OnENDERECOCLIENTEChanged();
            }
        }
        private global::System.String _ENDERECOCLIENTE;
        partial void OnENDERECOCLIENTEChanging(global::System.String value);
        partial void OnENDERECOCLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BAIRRO
        {
            get
            {
                return _BAIRRO;
            }
            set
            {
                OnBAIRROChanging(value);
                ReportPropertyChanging("BAIRRO");
                _BAIRRO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BAIRRO");
                OnBAIRROChanged();
            }
        }
        private global::System.String _BAIRRO;
        partial void OnBAIRROChanging(global::System.String value);
        partial void OnBAIRROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CEP
        {
            get
            {
                return _CEP;
            }
            set
            {
                OnCEPChanging(value);
                ReportPropertyChanging("CEP");
                _CEP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CEP");
                OnCEPChanged();
            }
        }
        private global::System.String _CEP;
        partial void OnCEPChanging(global::System.String value);
        partial void OnCEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELEFONECLIENTE
        {
            get
            {
                return _TELEFONECLIENTE;
            }
            set
            {
                OnTELEFONECLIENTEChanging(value);
                ReportPropertyChanging("TELEFONECLIENTE");
                _TELEFONECLIENTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELEFONECLIENTE");
                OnTELEFONECLIENTEChanged();
            }
        }
        private global::System.String _TELEFONECLIENTE;
        partial void OnTELEFONECLIENTEChanging(global::System.String value);
        partial void OnTELEFONECLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CELULARCLIENTE
        {
            get
            {
                return _CELULARCLIENTE;
            }
            set
            {
                OnCELULARCLIENTEChanging(value);
                ReportPropertyChanging("CELULARCLIENTE");
                _CELULARCLIENTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CELULARCLIENTE");
                OnCELULARCLIENTEChanged();
            }
        }
        private global::System.String _CELULARCLIENTE;
        partial void OnCELULARCLIENTEChanging(global::System.String value);
        partial void OnCELULARCLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CIDADE
        {
            get
            {
                return _CIDADE;
            }
            set
            {
                OnCIDADEChanging(value);
                ReportPropertyChanging("CIDADE");
                _CIDADE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CIDADE");
                OnCIDADEChanged();
            }
        }
        private global::System.String _CIDADE;
        partial void OnCIDADEChanging(global::System.String value);
        partial void OnCIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UF
        {
            get
            {
                return _UF;
            }
            set
            {
                OnUFChanging(value);
                ReportPropertyChanging("UF");
                _UF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UF");
                OnUFChanged();
            }
        }
        private global::System.String _UF;
        partial void OnUFChanging(global::System.String value);
        partial void OnUFChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_VENDA_REFERENCE_CLIENTES", "VENDA")]
        public EntityCollection<VENDA> VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VENDA>("AUTOPECASModel.FK_VENDA_REFERENCE_CLIENTES", "VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VENDA>("AUTOPECASModel.FK_VENDA_REFERENCE_CLIENTES", "VENDA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AUTOPECASModel", Name="FORNECEDORES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FORNECEDORES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FORNECEDORES object.
        /// </summary>
        /// <param name="iDFORNECEDOR">Initial value of the IDFORNECEDOR property.</param>
        /// <param name="nOMEFORNECEDOR">Initial value of the NOMEFORNECEDOR property.</param>
        /// <param name="cNPJFORNECEDOR">Initial value of the CNPJFORNECEDOR property.</param>
        /// <param name="eNDERECOFORNECEDOR">Initial value of the ENDERECOFORNECEDOR property.</param>
        public static FORNECEDORES CreateFORNECEDORES(global::System.Int32 iDFORNECEDOR, global::System.String nOMEFORNECEDOR, global::System.String cNPJFORNECEDOR, global::System.String eNDERECOFORNECEDOR)
        {
            FORNECEDORES fORNECEDORES = new FORNECEDORES();
            fORNECEDORES.IDFORNECEDOR = iDFORNECEDOR;
            fORNECEDORES.NOMEFORNECEDOR = nOMEFORNECEDOR;
            fORNECEDORES.CNPJFORNECEDOR = cNPJFORNECEDOR;
            fORNECEDORES.ENDERECOFORNECEDOR = eNDERECOFORNECEDOR;
            return fORNECEDORES;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFORNECEDOR
        {
            get
            {
                return _IDFORNECEDOR;
            }
            set
            {
                if (_IDFORNECEDOR != value)
                {
                    OnIDFORNECEDORChanging(value);
                    ReportPropertyChanging("IDFORNECEDOR");
                    _IDFORNECEDOR = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFORNECEDOR");
                    OnIDFORNECEDORChanged();
                }
            }
        }
        private global::System.Int32 _IDFORNECEDOR;
        partial void OnIDFORNECEDORChanging(global::System.Int32 value);
        partial void OnIDFORNECEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMEFORNECEDOR
        {
            get
            {
                return _NOMEFORNECEDOR;
            }
            set
            {
                OnNOMEFORNECEDORChanging(value);
                ReportPropertyChanging("NOMEFORNECEDOR");
                _NOMEFORNECEDOR = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMEFORNECEDOR");
                OnNOMEFORNECEDORChanged();
            }
        }
        private global::System.String _NOMEFORNECEDOR;
        partial void OnNOMEFORNECEDORChanging(global::System.String value);
        partial void OnNOMEFORNECEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CNPJFORNECEDOR
        {
            get
            {
                return _CNPJFORNECEDOR;
            }
            set
            {
                OnCNPJFORNECEDORChanging(value);
                ReportPropertyChanging("CNPJFORNECEDOR");
                _CNPJFORNECEDOR = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CNPJFORNECEDOR");
                OnCNPJFORNECEDORChanged();
            }
        }
        private global::System.String _CNPJFORNECEDOR;
        partial void OnCNPJFORNECEDORChanging(global::System.String value);
        partial void OnCNPJFORNECEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ENDERECOFORNECEDOR
        {
            get
            {
                return _ENDERECOFORNECEDOR;
            }
            set
            {
                OnENDERECOFORNECEDORChanging(value);
                ReportPropertyChanging("ENDERECOFORNECEDOR");
                _ENDERECOFORNECEDOR = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ENDERECOFORNECEDOR");
                OnENDERECOFORNECEDORChanged();
            }
        }
        private global::System.String _ENDERECOFORNECEDOR;
        partial void OnENDERECOFORNECEDORChanging(global::System.String value);
        partial void OnENDERECOFORNECEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BAIRROFORNECEDOR
        {
            get
            {
                return _BAIRROFORNECEDOR;
            }
            set
            {
                OnBAIRROFORNECEDORChanging(value);
                ReportPropertyChanging("BAIRROFORNECEDOR");
                _BAIRROFORNECEDOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BAIRROFORNECEDOR");
                OnBAIRROFORNECEDORChanged();
            }
        }
        private global::System.String _BAIRROFORNECEDOR;
        partial void OnBAIRROFORNECEDORChanging(global::System.String value);
        partial void OnBAIRROFORNECEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEPFORNECEDOR
        {
            get
            {
                return _CEPFORNECEDOR;
            }
            set
            {
                OnCEPFORNECEDORChanging(value);
                ReportPropertyChanging("CEPFORNECEDOR");
                _CEPFORNECEDOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEPFORNECEDOR");
                OnCEPFORNECEDORChanged();
            }
        }
        private global::System.String _CEPFORNECEDOR;
        partial void OnCEPFORNECEDORChanging(global::System.String value);
        partial void OnCEPFORNECEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELEFONEFIXO
        {
            get
            {
                return _TELEFONEFIXO;
            }
            set
            {
                OnTELEFONEFIXOChanging(value);
                ReportPropertyChanging("TELEFONEFIXO");
                _TELEFONEFIXO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELEFONEFIXO");
                OnTELEFONEFIXOChanged();
            }
        }
        private global::System.String _TELEFONEFIXO;
        partial void OnTELEFONEFIXOChanging(global::System.String value);
        partial void OnTELEFONEFIXOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELEFONECELULAR
        {
            get
            {
                return _TELEFONECELULAR;
            }
            set
            {
                OnTELEFONECELULARChanging(value);
                ReportPropertyChanging("TELEFONECELULAR");
                _TELEFONECELULAR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELEFONECELULAR");
                OnTELEFONECELULARChanged();
            }
        }
        private global::System.String _TELEFONECELULAR;
        partial void OnTELEFONECELULARChanging(global::System.String value);
        partial void OnTELEFONECELULARChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATACONTRATO
        {
            get
            {
                return _DATACONTRATO;
            }
            set
            {
                OnDATACONTRATOChanging(value);
                ReportPropertyChanging("DATACONTRATO");
                _DATACONTRATO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATACONTRATO");
                OnDATACONTRATOChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATACONTRATO;
        partial void OnDATACONTRATOChanging(Nullable<global::System.DateTime> value);
        partial void OnDATACONTRATOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_Pecas_Fornecedores", "PECAS")]
        public EntityCollection<PECAS> PECAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PECAS>("AUTOPECASModel.FK_Pecas_Fornecedores", "PECAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PECAS>("AUTOPECASModel.FK_Pecas_Fornecedores", "PECAS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AUTOPECASModel", Name="ITENSVENDA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ITENSVENDA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ITENSVENDA object.
        /// </summary>
        /// <param name="iDITENSVENDA">Initial value of the IDITENSVENDA property.</param>
        /// <param name="iDPECA">Initial value of the IDPECA property.</param>
        /// <param name="pRECOUNITARIO">Initial value of the PRECOUNITARIO property.</param>
        /// <param name="qUANTIDADE">Initial value of the QUANTIDADE property.</param>
        /// <param name="sUBTOTAL">Initial value of the SUBTOTAL property.</param>
        public static ITENSVENDA CreateITENSVENDA(global::System.Int32 iDITENSVENDA, global::System.Int32 iDPECA, global::System.Decimal pRECOUNITARIO, global::System.Int32 qUANTIDADE, global::System.Decimal sUBTOTAL)
        {
            ITENSVENDA iTENSVENDA = new ITENSVENDA();
            iTENSVENDA.IDITENSVENDA = iDITENSVENDA;
            iTENSVENDA.IDPECA = iDPECA;
            iTENSVENDA.PRECOUNITARIO = pRECOUNITARIO;
            iTENSVENDA.QUANTIDADE = qUANTIDADE;
            iTENSVENDA.SUBTOTAL = sUBTOTAL;
            return iTENSVENDA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDITENSVENDA
        {
            get
            {
                return _IDITENSVENDA;
            }
            set
            {
                if (_IDITENSVENDA != value)
                {
                    OnIDITENSVENDAChanging(value);
                    ReportPropertyChanging("IDITENSVENDA");
                    _IDITENSVENDA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDITENSVENDA");
                    OnIDITENSVENDAChanged();
                }
            }
        }
        private global::System.Int32 _IDITENSVENDA;
        partial void OnIDITENSVENDAChanging(global::System.Int32 value);
        partial void OnIDITENSVENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPECA
        {
            get
            {
                return _IDPECA;
            }
            set
            {
                OnIDPECAChanging(value);
                ReportPropertyChanging("IDPECA");
                _IDPECA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPECA");
                OnIDPECAChanged();
            }
        }
        private global::System.Int32 _IDPECA;
        partial void OnIDPECAChanging(global::System.Int32 value);
        partial void OnIDPECAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDVENDA
        {
            get
            {
                return _IDVENDA;
            }
            set
            {
                OnIDVENDAChanging(value);
                ReportPropertyChanging("IDVENDA");
                _IDVENDA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDVENDA");
                OnIDVENDAChanged();
            }
        }
        private Nullable<global::System.Int32> _IDVENDA;
        partial void OnIDVENDAChanging(Nullable<global::System.Int32> value);
        partial void OnIDVENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PRECOUNITARIO
        {
            get
            {
                return _PRECOUNITARIO;
            }
            set
            {
                OnPRECOUNITARIOChanging(value);
                ReportPropertyChanging("PRECOUNITARIO");
                _PRECOUNITARIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRECOUNITARIO");
                OnPRECOUNITARIOChanged();
            }
        }
        private global::System.Decimal _PRECOUNITARIO;
        partial void OnPRECOUNITARIOChanging(global::System.Decimal value);
        partial void OnPRECOUNITARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QUANTIDADE
        {
            get
            {
                return _QUANTIDADE;
            }
            set
            {
                OnQUANTIDADEChanging(value);
                ReportPropertyChanging("QUANTIDADE");
                _QUANTIDADE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QUANTIDADE");
                OnQUANTIDADEChanged();
            }
        }
        private global::System.Int32 _QUANTIDADE;
        partial void OnQUANTIDADEChanging(global::System.Int32 value);
        partial void OnQUANTIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SUBTOTAL
        {
            get
            {
                return _SUBTOTAL;
            }
            set
            {
                OnSUBTOTALChanging(value);
                ReportPropertyChanging("SUBTOTAL");
                _SUBTOTAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUBTOTAL");
                OnSUBTOTALChanged();
            }
        }
        private global::System.Decimal _SUBTOTAL;
        partial void OnSUBTOTALChanging(global::System.Decimal value);
        partial void OnSUBTOTALChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_ITENSVEN_REFERENCE_VENDA", "VENDA")]
        public VENDA VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDA>("AUTOPECASModel.FK_ITENSVEN_REFERENCE_VENDA", "VENDA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDA>("AUTOPECASModel.FK_ITENSVEN_REFERENCE_VENDA", "VENDA").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VENDA> VENDAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDA>("AUTOPECASModel.FK_ITENSVEN_REFERENCE_VENDA", "VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VENDA>("AUTOPECASModel.FK_ITENSVEN_REFERENCE_VENDA", "VENDA", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_ItensVenda_Pecas", "PECAS")]
        public PECAS PECAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PECAS>("AUTOPECASModel.FK_ItensVenda_Pecas", "PECAS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PECAS>("AUTOPECASModel.FK_ItensVenda_Pecas", "PECAS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PECAS> PECASReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PECAS>("AUTOPECASModel.FK_ItensVenda_Pecas", "PECAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PECAS>("AUTOPECASModel.FK_ItensVenda_Pecas", "PECAS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AUTOPECASModel", Name="PECAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PECAS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PECAS object.
        /// </summary>
        /// <param name="iDPECA">Initial value of the IDPECA property.</param>
        /// <param name="nOMEPECA">Initial value of the NOMEPECA property.</param>
        /// <param name="iDFORNECEDOR">Initial value of the IDFORNECEDOR property.</param>
        public static PECAS CreatePECAS(global::System.Int32 iDPECA, global::System.String nOMEPECA, global::System.Int32 iDFORNECEDOR)
        {
            PECAS pECAS = new PECAS();
            pECAS.IDPECA = iDPECA;
            pECAS.NOMEPECA = nOMEPECA;
            pECAS.IDFORNECEDOR = iDFORNECEDOR;
            return pECAS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPECA
        {
            get
            {
                return _IDPECA;
            }
            set
            {
                if (_IDPECA != value)
                {
                    OnIDPECAChanging(value);
                    ReportPropertyChanging("IDPECA");
                    _IDPECA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDPECA");
                    OnIDPECAChanged();
                }
            }
        }
        private global::System.Int32 _IDPECA;
        partial void OnIDPECAChanging(global::System.Int32 value);
        partial void OnIDPECAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMEPECA
        {
            get
            {
                return _NOMEPECA;
            }
            set
            {
                OnNOMEPECAChanging(value);
                ReportPropertyChanging("NOMEPECA");
                _NOMEPECA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMEPECA");
                OnNOMEPECAChanged();
            }
        }
        private global::System.String _NOMEPECA;
        partial void OnNOMEPECAChanging(global::System.String value);
        partial void OnNOMEPECAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFORNECEDOR
        {
            get
            {
                return _IDFORNECEDOR;
            }
            set
            {
                OnIDFORNECEDORChanging(value);
                ReportPropertyChanging("IDFORNECEDOR");
                _IDFORNECEDOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDFORNECEDOR");
                OnIDFORNECEDORChanged();
            }
        }
        private global::System.Int32 _IDFORNECEDOR;
        partial void OnIDFORNECEDORChanging(global::System.Int32 value);
        partial void OnIDFORNECEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDVEICULO
        {
            get
            {
                return _IDVEICULO;
            }
            set
            {
                OnIDVEICULOChanging(value);
                ReportPropertyChanging("IDVEICULO");
                _IDVEICULO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDVEICULO");
                OnIDVEICULOChanged();
            }
        }
        private Nullable<global::System.Int32> _IDVEICULO;
        partial void OnIDVEICULOChanging(Nullable<global::System.Int32> value);
        partial void OnIDVEICULOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QUANTIDADE
        {
            get
            {
                return _QUANTIDADE;
            }
            set
            {
                OnQUANTIDADEChanging(value);
                ReportPropertyChanging("QUANTIDADE");
                _QUANTIDADE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QUANTIDADE");
                OnQUANTIDADEChanged();
            }
        }
        private Nullable<global::System.Int32> _QUANTIDADE;
        partial void OnQUANTIDADEChanging(Nullable<global::System.Int32> value);
        partial void OnQUANTIDADEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PRECOPECA
        {
            get
            {
                return _PRECOPECA;
            }
            set
            {
                OnPRECOPECAChanging(value);
                ReportPropertyChanging("PRECOPECA");
                _PRECOPECA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRECOPECA");
                OnPRECOPECAChanged();
            }
        }
        private Nullable<global::System.Decimal> _PRECOPECA;
        partial void OnPRECOPECAChanging(Nullable<global::System.Decimal> value);
        partial void OnPRECOPECAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCATEGORIA
        {
            get
            {
                return _IDCATEGORIA;
            }
            set
            {
                OnIDCATEGORIAChanging(value);
                ReportPropertyChanging("IDCATEGORIA");
                _IDCATEGORIA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCATEGORIA");
                OnIDCATEGORIAChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCATEGORIA;
        partial void OnIDCATEGORIAChanging(Nullable<global::System.Int32> value);
        partial void OnIDCATEGORIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PRECOESTOCADO
        {
            get
            {
                return _PRECOESTOCADO;
            }
            set
            {
                OnPRECOESTOCADOChanging(value);
                ReportPropertyChanging("PRECOESTOCADO");
                _PRECOESTOCADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRECOESTOCADO");
                OnPRECOESTOCADOChanged();
            }
        }
        private Nullable<global::System.Decimal> _PRECOESTOCADO;
        partial void OnPRECOESTOCADOChanging(Nullable<global::System.Decimal> value);
        partial void OnPRECOESTOCADOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_Pecas_Categorias1", "CATEGORIAS")]
        public CATEGORIAS CATEGORIAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIAS>("AUTOPECASModel.FK_Pecas_Categorias1", "CATEGORIAS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIAS>("AUTOPECASModel.FK_Pecas_Categorias1", "CATEGORIAS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CATEGORIAS> CATEGORIASReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CATEGORIAS>("AUTOPECASModel.FK_Pecas_Categorias1", "CATEGORIAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CATEGORIAS>("AUTOPECASModel.FK_Pecas_Categorias1", "CATEGORIAS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_Pecas_Fornecedores", "FORNECEDORES")]
        public FORNECEDORES FORNECEDORES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FORNECEDORES>("AUTOPECASModel.FK_Pecas_Fornecedores", "FORNECEDORES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FORNECEDORES>("AUTOPECASModel.FK_Pecas_Fornecedores", "FORNECEDORES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FORNECEDORES> FORNECEDORESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FORNECEDORES>("AUTOPECASModel.FK_Pecas_Fornecedores", "FORNECEDORES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FORNECEDORES>("AUTOPECASModel.FK_Pecas_Fornecedores", "FORNECEDORES", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_ItensVenda_Pecas", "ITENSVENDA")]
        public EntityCollection<ITENSVENDA> ITENSVENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ITENSVENDA>("AUTOPECASModel.FK_ItensVenda_Pecas", "ITENSVENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ITENSVENDA>("AUTOPECASModel.FK_ItensVenda_Pecas", "ITENSVENDA", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_Pecas_Veiculos", "VEICULOS")]
        public VEICULOS VEICULOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VEICULOS>("AUTOPECASModel.FK_Pecas_Veiculos", "VEICULOS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VEICULOS>("AUTOPECASModel.FK_Pecas_Veiculos", "VEICULOS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VEICULOS> VEICULOSReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VEICULOS>("AUTOPECASModel.FK_Pecas_Veiculos", "VEICULOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VEICULOS>("AUTOPECASModel.FK_Pecas_Veiculos", "VEICULOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AUTOPECASModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AUTOPECASModel", Name="VEICULOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VEICULOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VEICULOS object.
        /// </summary>
        /// <param name="iDVEICULO">Initial value of the IDVEICULO property.</param>
        /// <param name="nOMEVEICULO">Initial value of the NOMEVEICULO property.</param>
        /// <param name="fABRICANTE">Initial value of the FABRICANTE property.</param>
        /// <param name="aNOINICIAL">Initial value of the ANOINICIAL property.</param>
        public static VEICULOS CreateVEICULOS(global::System.Int32 iDVEICULO, global::System.String nOMEVEICULO, global::System.String fABRICANTE, global::System.DateTime aNOINICIAL)
        {
            VEICULOS vEICULOS = new VEICULOS();
            vEICULOS.IDVEICULO = iDVEICULO;
            vEICULOS.NOMEVEICULO = nOMEVEICULO;
            vEICULOS.FABRICANTE = fABRICANTE;
            vEICULOS.ANOINICIAL = aNOINICIAL;
            return vEICULOS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDVEICULO
        {
            get
            {
                return _IDVEICULO;
            }
            set
            {
                if (_IDVEICULO != value)
                {
                    OnIDVEICULOChanging(value);
                    ReportPropertyChanging("IDVEICULO");
                    _IDVEICULO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDVEICULO");
                    OnIDVEICULOChanged();
                }
            }
        }
        private global::System.Int32 _IDVEICULO;
        partial void OnIDVEICULOChanging(global::System.Int32 value);
        partial void OnIDVEICULOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMEVEICULO
        {
            get
            {
                return _NOMEVEICULO;
            }
            set
            {
                OnNOMEVEICULOChanging(value);
                ReportPropertyChanging("NOMEVEICULO");
                _NOMEVEICULO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMEVEICULO");
                OnNOMEVEICULOChanged();
            }
        }
        private global::System.String _NOMEVEICULO;
        partial void OnNOMEVEICULOChanging(global::System.String value);
        partial void OnNOMEVEICULOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FABRICANTE
        {
            get
            {
                return _FABRICANTE;
            }
            set
            {
                OnFABRICANTEChanging(value);
                ReportPropertyChanging("FABRICANTE");
                _FABRICANTE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FABRICANTE");
                OnFABRICANTEChanged();
            }
        }
        private global::System.String _FABRICANTE;
        partial void OnFABRICANTEChanging(global::System.String value);
        partial void OnFABRICANTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ANOINICIAL
        {
            get
            {
                return _ANOINICIAL;
            }
            set
            {
                OnANOINICIALChanging(value);
                ReportPropertyChanging("ANOINICIAL");
                _ANOINICIAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ANOINICIAL");
                OnANOINICIALChanged();
            }
        }
        private global::System.DateTime _ANOINICIAL;
        partial void OnANOINICIALChanging(global::System.DateTime value);
        partial void OnANOINICIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ANOFINAL
        {
            get
            {
                return _ANOFINAL;
            }
            set
            {
                OnANOFINALChanging(value);
                ReportPropertyChanging("ANOFINAL");
                _ANOFINAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ANOFINAL");
                OnANOFINALChanged();
            }
        }
        private Nullable<global::System.DateTime> _ANOFINAL;
        partial void OnANOFINALChanging(Nullable<global::System.DateTime> value);
        partial void OnANOFINALChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_Pecas_Veiculos", "PECAS")]
        public EntityCollection<PECAS> PECAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PECAS>("AUTOPECASModel.FK_Pecas_Veiculos", "PECAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PECAS>("AUTOPECASModel.FK_Pecas_Veiculos", "PECAS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AUTOPECASModel", Name="VENDA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VENDA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VENDA object.
        /// </summary>
        /// <param name="iDVENDA">Initial value of the IDVENDA property.</param>
        public static VENDA CreateVENDA(global::System.Int32 iDVENDA)
        {
            VENDA vENDA = new VENDA();
            vENDA.IDVENDA = iDVENDA;
            return vENDA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDVENDA
        {
            get
            {
                return _IDVENDA;
            }
            set
            {
                if (_IDVENDA != value)
                {
                    OnIDVENDAChanging(value);
                    ReportPropertyChanging("IDVENDA");
                    _IDVENDA = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDVENDA");
                    OnIDVENDAChanged();
                }
            }
        }
        private global::System.Int32 _IDVENDA;
        partial void OnIDVENDAChanging(global::System.Int32 value);
        partial void OnIDVENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDVENDEDOR
        {
            get
            {
                return _IDVENDEDOR;
            }
            set
            {
                OnIDVENDEDORChanging(value);
                ReportPropertyChanging("IDVENDEDOR");
                _IDVENDEDOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDVENDEDOR");
                OnIDVENDEDORChanged();
            }
        }
        private Nullable<global::System.Int32> _IDVENDEDOR;
        partial void OnIDVENDEDORChanging(Nullable<global::System.Int32> value);
        partial void OnIDVENDEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATAVENDA
        {
            get
            {
                return _DATAVENDA;
            }
            set
            {
                OnDATAVENDAChanging(value);
                ReportPropertyChanging("DATAVENDA");
                _DATAVENDA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATAVENDA");
                OnDATAVENDAChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATAVENDA;
        partial void OnDATAVENDAChanging(Nullable<global::System.DateTime> value);
        partial void OnDATAVENDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDCLIENTE
        {
            get
            {
                return _IDCLIENTE;
            }
            set
            {
                OnIDCLIENTEChanging(value);
                ReportPropertyChanging("IDCLIENTE");
                _IDCLIENTE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCLIENTE");
                OnIDCLIENTEChanged();
            }
        }
        private Nullable<global::System.Int32> _IDCLIENTE;
        partial void OnIDCLIENTEChanging(Nullable<global::System.Int32> value);
        partial void OnIDCLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PRECOTOTAL
        {
            get
            {
                return _PRECOTOTAL;
            }
            set
            {
                OnPRECOTOTALChanging(value);
                ReportPropertyChanging("PRECOTOTAL");
                _PRECOTOTAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRECOTOTAL");
                OnPRECOTOTALChanged();
            }
        }
        private Nullable<global::System.Decimal> _PRECOTOTAL;
        partial void OnPRECOTOTALChanging(Nullable<global::System.Decimal> value);
        partial void OnPRECOTOTALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DESCONTO
        {
            get
            {
                return _DESCONTO;
            }
            set
            {
                OnDESCONTOChanging(value);
                ReportPropertyChanging("DESCONTO");
                _DESCONTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DESCONTO");
                OnDESCONTOChanged();
            }
        }
        private Nullable<global::System.Double> _DESCONTO;
        partial void OnDESCONTOChanging(Nullable<global::System.Double> value);
        partial void OnDESCONTOChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_VENDA_REFERENCE_CLIENTES", "CLIENTES")]
        public CLIENTES CLIENTES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTES>("AUTOPECASModel.FK_VENDA_REFERENCE_CLIENTES", "CLIENTES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTES>("AUTOPECASModel.FK_VENDA_REFERENCE_CLIENTES", "CLIENTES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENTES> CLIENTESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENTES>("AUTOPECASModel.FK_VENDA_REFERENCE_CLIENTES", "CLIENTES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENTES>("AUTOPECASModel.FK_VENDA_REFERENCE_CLIENTES", "CLIENTES", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_ITENSVEN_REFERENCE_VENDA", "ITENSVENDA")]
        public EntityCollection<ITENSVENDA> ITENSVENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ITENSVENDA>("AUTOPECASModel.FK_ITENSVEN_REFERENCE_VENDA", "ITENSVENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ITENSVENDA>("AUTOPECASModel.FK_ITENSVEN_REFERENCE_VENDA", "ITENSVENDA", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_VENDA_REFERENCE_VENDEDOR", "VENDEDORES")]
        public VENDEDORES VENDEDORES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDEDORES>("AUTOPECASModel.FK_VENDA_REFERENCE_VENDEDOR", "VENDEDORES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDEDORES>("AUTOPECASModel.FK_VENDA_REFERENCE_VENDEDOR", "VENDEDORES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VENDEDORES> VENDEDORESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VENDEDORES>("AUTOPECASModel.FK_VENDA_REFERENCE_VENDEDOR", "VENDEDORES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VENDEDORES>("AUTOPECASModel.FK_VENDA_REFERENCE_VENDEDOR", "VENDEDORES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AUTOPECASModel", Name="VENDEDORES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VENDEDORES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VENDEDORES object.
        /// </summary>
        /// <param name="iDVENDEDOR">Initial value of the IDVENDEDOR property.</param>
        /// <param name="nOMEVENDEDOR">Initial value of the NOMEVENDEDOR property.</param>
        /// <param name="n_CADASTRO">Initial value of the N_CADASTRO property.</param>
        /// <param name="dATAADM">Initial value of the DATAADM property.</param>
        public static VENDEDORES CreateVENDEDORES(global::System.Int32 iDVENDEDOR, global::System.String nOMEVENDEDOR, global::System.Int32 n_CADASTRO, global::System.DateTime dATAADM)
        {
            VENDEDORES vENDEDORES = new VENDEDORES();
            vENDEDORES.IDVENDEDOR = iDVENDEDOR;
            vENDEDORES.NOMEVENDEDOR = nOMEVENDEDOR;
            vENDEDORES.N_CADASTRO = n_CADASTRO;
            vENDEDORES.DATAADM = dATAADM;
            return vENDEDORES;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDVENDEDOR
        {
            get
            {
                return _IDVENDEDOR;
            }
            set
            {
                if (_IDVENDEDOR != value)
                {
                    OnIDVENDEDORChanging(value);
                    ReportPropertyChanging("IDVENDEDOR");
                    _IDVENDEDOR = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDVENDEDOR");
                    OnIDVENDEDORChanged();
                }
            }
        }
        private global::System.Int32 _IDVENDEDOR;
        partial void OnIDVENDEDORChanging(global::System.Int32 value);
        partial void OnIDVENDEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMEVENDEDOR
        {
            get
            {
                return _NOMEVENDEDOR;
            }
            set
            {
                OnNOMEVENDEDORChanging(value);
                ReportPropertyChanging("NOMEVENDEDOR");
                _NOMEVENDEDOR = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMEVENDEDOR");
                OnNOMEVENDEDORChanged();
            }
        }
        private global::System.String _NOMEVENDEDOR;
        partial void OnNOMEVENDEDORChanging(global::System.String value);
        partial void OnNOMEVENDEDORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 N_CADASTRO
        {
            get
            {
                return _N_CADASTRO;
            }
            set
            {
                OnN_CADASTROChanging(value);
                ReportPropertyChanging("N_CADASTRO");
                _N_CADASTRO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("N_CADASTRO");
                OnN_CADASTROChanged();
            }
        }
        private global::System.Int32 _N_CADASTRO;
        partial void OnN_CADASTROChanging(global::System.Int32 value);
        partial void OnN_CADASTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATAADM
        {
            get
            {
                return _DATAADM;
            }
            set
            {
                OnDATAADMChanging(value);
                ReportPropertyChanging("DATAADM");
                _DATAADM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATAADM");
                OnDATAADMChanged();
            }
        }
        private global::System.DateTime _DATAADM;
        partial void OnDATAADMChanging(global::System.DateTime value);
        partial void OnDATAADMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ENDERECO
        {
            get
            {
                return _ENDERECO;
            }
            set
            {
                OnENDERECOChanging(value);
                ReportPropertyChanging("ENDERECO");
                _ENDERECO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ENDERECO");
                OnENDERECOChanged();
            }
        }
        private global::System.String _ENDERECO;
        partial void OnENDERECOChanging(global::System.String value);
        partial void OnENDERECOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELFIXO
        {
            get
            {
                return _TELFIXO;
            }
            set
            {
                OnTELFIXOChanging(value);
                ReportPropertyChanging("TELFIXO");
                _TELFIXO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELFIXO");
                OnTELFIXOChanged();
            }
        }
        private global::System.String _TELFIXO;
        partial void OnTELFIXOChanging(global::System.String value);
        partial void OnTELFIXOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELCEL
        {
            get
            {
                return _TELCEL;
            }
            set
            {
                OnTELCELChanging(value);
                ReportPropertyChanging("TELCEL");
                _TELCEL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELCEL");
                OnTELCELChanged();
            }
        }
        private global::System.String _TELCEL;
        partial void OnTELCELChanging(global::System.String value);
        partial void OnTELCELChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ESTADOCIVIL
        {
            get
            {
                return _ESTADOCIVIL;
            }
            set
            {
                OnESTADOCIVILChanging(value);
                ReportPropertyChanging("ESTADOCIVIL");
                _ESTADOCIVIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ESTADOCIVIL");
                OnESTADOCIVILChanged();
            }
        }
        private global::System.String _ESTADOCIVIL;
        partial void OnESTADOCIVILChanging(global::System.String value);
        partial void OnESTADOCIVILChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AUTOPECASModel", "FK_VENDA_REFERENCE_VENDEDOR", "VENDA")]
        public EntityCollection<VENDA> VENDA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VENDA>("AUTOPECASModel.FK_VENDA_REFERENCE_VENDEDOR", "VENDA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VENDA>("AUTOPECASModel.FK_VENDA_REFERENCE_VENDEDOR", "VENDA", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
